# phrases.py

CONFIRMATION_PHRASES = [
    "That makes a lot of sense in this position.", "This feels like a very solid choice.",
    "I like the look of that move.", "That sounds like a good move to me.",
    "This seems like the most natural continuation.", "I'd definitely consider that line.",
    "That's a very reasonable way to play.", "I see where you're going with that.",
    "That looks like a sturdy response.", "I'm leaning towards that being correct.",
    "That fits the needs of the position.", "A very logical follow-up.",
    "That looks quite promising.", "I think that's a sound approach.",
    "That move has a lot of merit.", "I'm on board with that idea.",
    "That seems like a safe bet.", "I like the logic behind that.",
    "That's a clever way to handle things.", "I'd play that without much hesitation.",
    "It’s a very human-like decision.", "That's a strong positional shout.",
    "I can't see any immediate reason to dislike that.", "That looks like a high-quality move.",
    "It addresses the immediate concerns well.", "I think that keeps the balance perfectly.",
    "That's a very intuitive response.", "I'm liking the pressure that move creates.",
    "It feels like you've found the right idea.", "That's a very respectable choice.",
    "I would be happy to play that move myself.", "It looks like you've got the right plan.",
    "That’s a very sensible way to continue.", "It seems like a very professional move.",
    "That choice shows a good understanding of the board.", "I think that’s the most consistent move.",
    "It’s hard to argue against that logic.", "That move really stabilizes things.",
    "I see no reason to play anything else.", "That feels like the most principled move.",
    "It’s a very clean way to progress.", "That move makes total sense intuitively.",
    "I think that's a very insightful choice.", "It seems like you've grasped the position.",
    "That's a very solid way to navigate this.", "I'm a fan of that move's efficiency.",
    "It looks like a very well-reasoned decision.", "That's a very sharp and logical move.",
    "I think that's exactly what the position calls for.", "It’s a very standard and reliable move.",
    "That looks like a very polished response.", "I'm in total agreement with that move.",
    "It’s a very smart way to handle the tension.", "That move feels very right for this setup.",
    "I think that's a very sophisticated choice.", "It seems like a very grounded move.",
    "That's a very mature way to play the position.", "I like how that move simplifies things.",
    "It feels like a very confident choice.", "That's a very sound tactical decision.",
    "I think that's a very balanced move.", "It seems like the most straightforward path.",
    "That move has a lot of hidden strength.", "I'm impressed by that logical choice.",
    "It’s a very sturdy and dependable move.", "That looks like a very precise response.",
    "I think that's a very clever find.", "It seems like a very natural fit.",
    "That move shows a lot of tactical awareness.", "I'm quite fond of that continuation.",
    "It feels like a very deliberate choice.", "That's a very well-judged move.",
    "I think that's a very effective response.", "It seems like a very calculated move.",
    "That move really clarifies the situation.", "I'm liking the direction you're taking.",
    "It feels like a very objective choice.", "That's a very sharp way to proceed.",
    "I think that's a very sturdy way to play.", "It seems like a very reliable choice.",
    "That move has a lot of common sense behind it.", "I'm on the same page with that move.",
    "It feels like a very strategic choice.", "That's a very tidy way to play.",
    "I think that's a very prudent move.", "It seems like a very honest response.",
    "That move really hits the mark.", "I'm in favor of that logical approach.",
    "It feels like a very robust choice.", "That's a very clear-headed move.",
    "I think that's a very direct response.", "It seems like a very thoughtful move.",
    "That move shows a lot of positional sense.", "I'm supportive of that choice.",
    "It feels like a very appropriate move.", "That's a very neat way to handle it.",
    "I think that's a very sensible decision.", "It seems like a very practical move.",
    "That move really flows with the position.", "I'm convinced by that logic.",
    "It feels like a very disciplined choice.", "That's a very focused move.",
    "I think that's a very sharp-eyed choice.", "It seems like a very coherent move.",
    "That move has a lot of professional feel.", "I'm liking the simplicity of that.",
    "It feels like a very strong-willed move.", "That's a very astute choice.",
    "I think that's a very capable move.", "It seems like a very solid foundation.",
    "That move really anchors the position.", "I'm a big fan of that logical path.",
    "It feels like a very well-aimed move.", "That's a very graceful way to play.",
    "I think that's a very nimble response.", "It seems like a very alert move.",
    "That move shows a lot of foresight.", "I'm on board with that strategy.",
    "It feels like a very sturdy continuation.", "That's a very elegant move.",
    "I think that's a very refined choice.", "It seems like a very savvy move.",
    "That move really hits the nail on the head.", "I'm impressed by the logic here.",
    "It feels like a very reliable way forward.", "That's a very courageous move.",
    "I think that's a very direct way to play.", "It seems like a very brave choice.",
    "That move has a lot of character.", "I'm liking the energy of that move.",
    "It feels like a very dynamic choice.", "That's a very active move.",
    "I think that's a very spirited response.", "It seems like a very bold move.",
    "That move really makes a statement.", "I'm in agreement with that plan.",
    "It feels like a very purposeful choice.", "That's a very intent move.",
    "I think that's a very decisive response.", "It seems like a very firm move.",
    "That move shows a lot of resolve.", "I'm liking the clarity of that.",
    "It feels like a very distinct choice.", "That's a very unique move.",
    "I think that's a very original response.", "It seems like a very fresh move.",
    "That move has a lot of creative energy.", "I'm on board with that vision.",
    "It feels like a very inspired choice.", "That's a very imaginative move.",
    "I think that's a very inventive response.", "It seems like a very clever move.",
    "That move really breaks the mold.", "I'm liking the novelty of that.",
    "It feels like a very artistic choice.", "That's a very poetic move.",
    "I think that's a very lyrical response.", "It seems like a very fluid move.",
    "That move has a lot of grace.", "I'm in awe of that logic.",
    "It feels like a very harmonious choice.", "That's a very balanced move.",
    "I think that's a very symmetrical response.", "It seems like a very rhythmic move.",
    "That move really ties it all together.", "I'm liking the flow of that.",
    "It feels like a very natural progression.", "That's a very intuitive move.",
    "I think that's a very instinctive response.", "It seems like a very visceral move.",
    "That move has a lot of raw power.", "I'm on board with that strength.",
    "It feels like a very potent choice.", "That's a very forceful move.",
    "I think that's a very commanding response.", "It seems like a very dominant move.",
    "That move really takes charge.", "I'm liking the authority of that.",
    "It feels like a very regal choice.", "That's a very noble move.",
    "I think that's a very dignified response.", "It seems like a very grand move.",
    "That move has a lot of stature.", "I'm in favor of that presence.",
    "It feels like a very substantial choice.", "That's a very weighty move.",
    "I think that's a very heavy response.", "It seems like a very serious move.",
    "That move really carries some weight.", "I'm liking the gravity of that.",
    "It feels like a very momentous choice.", "That's a very significant move.",
    "I think that's a very critical response.", "It seems like a very vital move.",
    "That move really matters right now.", "I'm on board with that importance.",
    "It feels like a very key choice.", "That's a short, pivotal move.",
    "I think that's a very essential response.", "It seems like a very fundamental move.",
    "That move really gets to the heart of it.", "I'm liking the core logic here.",
    "I can see that working out well.", "That's a very sturdy choice.",
    "It seems like a very balanced response.", "I'm leaning towards that idea.",
    "That makes sense positional-wise.", "I like the pressure that exerts.",
    "A very natural-looking move.", "That's a high-quality suggestion.",
    "It fits the context of the game.", "I'm quite comfortable with that move.",
    "That move really stabilizes the board.", "I think that's a very sound idea.",
    "I believe this is a strong line.", "This looks like a solid continuation.",
    "That's a very insightful way to play.", "I like how that move controls the board.",
    "A very logical step forward.", "I can see the merit in that move.",
    "That looks like a very professional choice.", "I'm in agreement with that strategy.",
    "That move has a lot of potential.", "It seems like a very mature decision.",
    "I'm liking the direction you're taking.", "That move really clarifies things.",
    "It feels like a very disciplined choice.", "That's a very sharp-eyed response.",
    "I think that's a very effective move.", "It seems like a very calculated response."
]
